language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - memcached
before_script:
  - travis_retry composer self-update
  - composer --prefer-source --dev install
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
branches:
  only:
  - master
  - develop
notifications:
  slack:
    secure: lv5Ih2lfcchQzBV9nyWMuoV4HLZh9fjBZwzbfWS9XKSnzLADwhMFXgDS0FCbptUx6qj7SjKPzAhZWcmPN/9skSg/8Vlnsj1S2XdxZnWTq+9CjAbo0lkcIWS8Q+YreB6bOV23s6i6fvX2zI0O5aRLrYma5eSgBuuwCmJp8zIht6k=
addons:
  code_climate:
    repo_token:
      secure: "IaXJwRuIRKO0qzE9kU+ROXjl6L0f0+AtsptdwQov+Aa0iyN2gVVzZS71lALf0GxQVeimzdHZEi9pA9GOUJL6sts/ynUNQ3KDj2fk6tTiHfcwlyfRoL1koWT9c+X7lyx3T8QcCytJvsnr/JGp59oH2sa2YI6U6aUFvm+/iJRTGgo="